// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.80.4

package store

import "github.com/jackc/pgx/v5/pgtype"

type Task struct {
	ID        int32              `json:"id"`
	Title     string             `json:"title"`
	Text      string             `json:"text"`
	Completed pgtype.Bool        `json:"completed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
