// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.80.4

package store

import (
	"database/sql"
)

type Task struct {
	ID        int32
	Title     string
	Text      sql.NullString
	Completed sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
