// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.80.4
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, text, completed)
VALUES ($1, $2, $3) RETURNING id, title, text, completed, created_at, updated_at
`

type CreateTaskParams struct {
	Title     string      `json:"title"`
	Text      string      `json:"text"`
	Completed pgtype.Bool `json:"completed"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Title, arg.Text, arg.Completed)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE
FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, text, completed, created_at, updated_at
FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, title, text, completed, created_at, updated_at
FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) GetTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Text,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title      = COALESCE($2, title),
    text       = COALESCE($3, text),
    completed  = COALESCE($4, completed),
    updated_at = NOW()
WHERE id = $1 RETURNING id, title, text, completed, created_at, updated_at
`

type UpdateTaskParams struct {
	ID        int32       `json:"id"`
	Title     string      `json:"title"`
	Text      string      `json:"text"`
	Completed pgtype.Bool `json:"completed"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Text,
		arg.Completed,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
